# Generated by Django 4.2.2 on 2023-06-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('format', 'format'), ('size', 'size')], max_length=100),
        ),
    ]
