# Generated by Django 4.2.2 on 2023-06-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_variation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='craeted_date',
            new_name='created_date',
        ),
    ]
