# Generated by Django 4.2.3 on 2023-07-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_variationprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variationprice',
            old_name='variation',
            new_name='get_variation_category',
        ),
    ]
