# Generated by Django 4.2.3 on 2023-07-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_variation_variationprice_get_variation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variationprice',
            old_name='get_variation_category',
            new_name='variation',
        ),
    ]
