# Generated by Django 4.2.3 on 2023-07-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_get_variation_category_variationprice_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationprice',
            name='variation',
        ),
        migrations.AddField(
            model_name='variationprice',
            name='variation_category',
            field=models.CharField(choices=[('0-9', '0-9'), ('10-15', '10-15'), ('6-10', '6-10')], default='10-15', max_length=50),
        ),
    ]
