# Generated by Django 4.1.7 on 2023-06-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('complated', 'complated'), ('Cancelled', 'Cancelled'), ('New', 'New')], default='New', max_length=50),
        ),
    ]
