# Generated by Django 4.2.2 on 2023-07-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_alter_orderproduct_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('New', 'New'), ('complated', 'complated'), ('Cancelled', 'Cancelled')], default='New', max_length=50),
        ),
    ]
