# Generated by Django 4.2.2 on 2023-07-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('complated', 'complated'), ('Cancelled', 'Cancelled'), ('New', 'New')], default='New', max_length=50),
        ),
    ]
