# Generated by Django 4.2.3 on 2023-07-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('complated', 'complated'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted')], default='New', max_length=50),
        ),
    ]
